apiVersion: apps/v1
kind: Deployment
metadata:
  name: evg-${myEnv}
  labels:
    app: evgen-app
    env: ${myEnv}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: evgen-app
  template:
    metadata:
      labels:
        app: evgen-app
    spec:
      containers:
      - name: evgen-app-cont
        image: ${dockerimagename}
        ports:
        - containerPort: 80
