apiVersion: apps/v1
kind: Deployment
metadata:
  name: evgen-deployment
  labels:
    app: evgen-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: evgen-app
  template:
    metadata:
      labels:
        app: evgen-app
    spec:
      containers:
      - name: evgen-app-cont
        image: zabdev/evgen:4.0
        ports:
        - containerPort: 80
          
